### ISSUE TITLE
no such file to load -- redis/connection/synchrony

### ISSUE THREAD

**Issue by andrew311** [igrigorik/mneme#1]
When I run mneme according to the readme, it fails to load a file that looks like it should be in the redis gem. Here's the error:

```
~$ mneme -p 9000 -sv -c config.rb
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- redis/connection/synchrony (LoadError)
from <internal:lib/rubygems/custom_require>:29:in `require'
from /usr/local/lib/ruby/gems/1.9.1/gems/mneme-0.5.0/bin/../lib/mneme.rb:5:in `<main>'
```

I can't find "synchrony" in the redis gem, not even in past versions. Any idea what's up?

**Comment by dj2** [comment]
You need Ilyas fork of the redis gem. It's available at (git://github.com/igrigorik/redis-rb.git) or, if you've checked mneme out from github you can bundle install which will pull in the right version of the redis gem.

**Comment by igrigorik** [comment]
Yep. Hoping to get the new driver changes merged soon, but until then, you'll need my fork.

**Comment by andrew311** [comment]
K, I updated the gem, but now I get a different file missing:

```
~$ mneme -p 9000 -sv -c config.rb
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- lib/mneme/helper (LoadError)
from <internal:lib/rubygems/custom_require>:29:in `require'
from /usr/local/lib/ruby/gems/1.9.1/gems/mneme-0.5.0/bin/../lib/mneme.rb:8:in `<main>'
```

**Comment by igrigorik** [comment]
Doh! Yep, ran into same issue today. Haven't had a chance to dig in yet, but on the agenda..

**Comment by igrigorik** [comment]
Fixed and released a new version. Sorry about the hassle. gem update mneme should do the trick.
